Repository Activiti/activiti-dependencies, pull requests merged in 2018-11, with the labels that each got.

#49 update org.activiti.core.common:activiti-core-common-dependencies to 7.0.6
  pom.xml
Labels: updatebot

#48 update org.activiti.api:activiti-api-dependencies to 7.0.36
  pom.xml
Labels: updatebot

#47 update org.activiti:activiti-core-dependencies to 7.0.57
  pom.xml
Labels: updatebot

#50 update org.activiti.api:activiti-api-dependencies to 7.0.37
  pom.xml
Labels: updatebot

#51 update org.activiti.core.common:activiti-core-common-dependencies to 7.0.7
  pom.xml
Labels: updatebot

#56 update org.activiti:activiti-core-dependencies to 7.0.63
  pom.xml
Labels: updatebot

#63 Create .mergify.yml
  .mergify.yml
Labels: enhancement, in progress

#66 feat: Enforce dependency version convergence for CI/CD pipelines
  .updatebot.yml
  dependencies-tests/pom.xml
  dependencies/pom.xml
  pom.xml
Labels: enhancement, in progress

#73 Create Makefile
  Jenkinsfile
  Makefile
Labels: in progress

#72 fix(versions): update Activiti/activiti-dependencies versions
  pom.xml
Labels: in progress, updatebot

#74 fix(versions): update Activiti/activiti-dependencies versions
  .mergify.yml
  dependencies-tests/pom.xml
  pom.xml
Labels: in progress, updatebot

#75 fix(versions): update Activiti/activiti-dependencies versions
  pom.xml
Labels: in progress, updatebot

#76 fix(versions): update Activiti/activiti-dependencies versions
  pom.xml
Labels: in progress, ready-to-merge, updatebot

#77 fix: enforce same parent version dependency
  .mergify.yml
  dependencies-tests/pom.xml
  pom.xml
Labels: enhancement, in progress

#78 fix(versions): update Activiti/activiti-dependencies versions
  .mergify.yml
  pom.xml
Labels: in progress, updatebot

#79 fix(versions): update Activiti/activiti-dependencies versions
  pom.xml
Labels: in progress, updatebot

#80 fix(versions): update Activiti/activiti-dependencies versions
  pom.xml
Labels: in progress, updatebot

#81 Automated tests for dependencies convergence in CI pipelines for Activiti Cloud
  .updatebot.yml
  dependencies-tests/pom.xml
  dependencies/pom.xml
  pom.xml
Labels: enhancement, in progress

#82 fix(versions): update Activiti/activiti-dependencies versions
  pom.xml
Labels: in progress, updatebot
